"""Pydantic schema models for all pipeline stages."""

from prism.schemas.enums import (
    ConflictResolution,
    ConfidenceScorer,
    EntityMergeStrategy,
    EntityType,
    ExtractionTier,
    LayerType,
    LLMProvider,
    RelationType,
    SemanticLevel,
    TokenType,
    TopicClustering,
)
from prism.schemas.global_pg import (
    AggregationConfig,
    ConfidenceSummary,
    GlobalPG,
    MergedEntity,
    PipelineConfig,
    Stage4Input,
    Stage4Output,
    TopicCluster,
)
from prism.schemas.physical import (
    BlockquoteComponent,
    CellPosition,
    CodeBlockComponent,
    DetectedLayersReport,
    DiagramComponent,
    EmphasisComponent,
    EmphasisType,
    FigureComponent,
    FootnoteComponent,
    HeadingComponent,
    HtmlBlockComponent,
    HtmlInlineComponent,
    InlineCodeComponent,
    LayerInstance,
    LinkComponent,
    LinkType,
    ListComponent,
    ListItem,
    ListStyle,
    MarkdownNode,
    MetadataComponent,
    NestingMatrix,
    NestingRule,
    NodeType,
    ParagraphComponent,
    PhysicalComponent,
    Stage2Input,
    Stage2Output,
    TableComponent,
    TableCell,
    TableRow,
    TopologyConfig,
)
from prism.schemas.semantic import (
    AlternativeHypothesis,
    Entity,
    MiniPG,
    MiniTopic,
    PredicateFrame,
    Relationship,
    SemanticConfig,
    SemanticTreeNode,
    Stage3Input,
    Stage3Output,
)
from prism.schemas.token import (
    Stage1Input,
    Stage1Output,
    Token,
    TokenMetadata,
    TokenizationConfig,
)

__all__ = [
    # Enums
    "ConflictResolution",
    "ConfidenceScorer",
    "EntityMergeStrategy",
    "EntityType",
    "ExtractionTier",
    "LayerType",
    "LLMProvider",
    "RelationType",
    "SemanticLevel",
    "TokenType",
    "TopicClustering",
    "NodeType",
    # Stage 1
    "Token",
    "TokenMetadata",
    "TokenizationConfig",
    "Stage1Input",
    "Stage1Output",
    # Stage 2
    "PhysicalComponent",
    "TopologyConfig",
    "Stage2Input",
    "Stage2Output",
    "MarkdownNode",
    "LayerInstance",
    "DetectedLayersReport",
    "NestingMatrix",
    "NestingRule",
    "NESTING_MATRIX",
    "CellPosition",
    "ListStyle",
    "ListItem",
    "TableCell",
    "TableRow",
    "TableComponent",
    "ListComponent",
    # Typed components (P2.6)
    "EmphasisType",
    "LinkType",
    "HeadingComponent",
    "ParagraphComponent",
    "CodeBlockComponent",
    "DiagramComponent",
    "FootnoteComponent",
    "MetadataComponent",
    "FigureComponent",
    "BlockquoteComponent",
    "InlineCodeComponent",
    "EmphasisComponent",
    "LinkComponent",
    "HtmlBlockComponent",
    "HtmlInlineComponent",
    # Stage 3
    "MiniTopic",
    "PredicateFrame",
    "Entity",
    "AlternativeHypothesis",
    "Relationship",
    "MiniPG",
    "SemanticTreeNode",
    "SemanticConfig",
    "Stage3Input",
    "Stage3Output",
    # Stage 4
    "TopicCluster",
    "MergedEntity",
    "ConfidenceSummary",
    "GlobalPG",
    "AggregationConfig",
    "Stage4Input",
    "Stage4Output",
    # Pipeline
    "PipelineConfig",
]
